#!/usr/bin/env python3
#===----------------------------------------------------------------------===#
#
# Part of the OpenCyphal project, under the MIT licence
# SPDX-License-Identifier: MIT
#
#===----------------------------------------------------------------------===#

"""Generate embedded MLIR catalog for standard UAVCAN namespace."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable

DEFAULT_REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_UAVCAN_ROOT = DEFAULT_REPO_ROOT / "submodules/public_regulated_data_types/uavcan"
DEFAULT_OUTPUT = DEFAULT_REPO_ROOT / "lib/CodeGen/UavcanEmbeddedMlir.inc"

DELIMITER = "LLVMDSDL_UAVCAN"

HEADER = """//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Auto-generated embedded UAVCAN MLIR catalog.
///
/// Generated by: tools/dsdlc/generate_embedded_uavcan_mlir.py
/// Source: submodules/public_regulated_data_types/uavcan
///
/// DO NOT EDIT MANUALLY.
//===----------------------------------------------------------------------===//

namespace llvmdsdl::uavcan_embedded_mlir
{{
inline constexpr std::size_t kEmbeddedUavcanSchemaCount = {schema_count}U;
inline constexpr const char  kEmbeddedUavcanMlirSha256[] = "{sha256}";
inline constexpr const char  kEmbeddedUavcanMlirText[] = R"{delimiter}(
{mlir_text}){delimiter}";
}}  // namespace llvmdsdl::uavcan_embedded_mlir
"""


def _find_default_dsdlc(repo_root: Path) -> str:
    candidates = [
        repo_root / "build/matrix/dev-homebrew/tools/dsdlc/RelWithDebInfo/dsdlc",
        repo_root / "build/matrix/dev-homebrew/tools/dsdlc/Debug/dsdlc",
    ]
    for candidate in candidates:
        if candidate.exists() and os.access(candidate, os.X_OK):
            return str(candidate)

    resolved = shutil.which("dsdlc")
    if resolved:
        return resolved

    return "dsdlc"


def _run_dsdlc(dsdlc: str, uavcan_root: Path) -> str:
    command = [dsdlc, "--target-language", "mlir", str(uavcan_root)]
    process = subprocess.run(command, capture_output=True, text=True, check=False)
    if process.returncode != 0:
        sys.stderr.write(process.stderr)
        raise RuntimeError(f"embedded-uavcan generation failed (rc={process.returncode})")

    text = process.stdout.replace("\r\n", "\n")
    if not text.endswith("\n"):
        text += "\n"

    if DELIMITER in text:
        raise RuntimeError("embedded-uavcan generation failed: MLIR text contains raw-string delimiter token")

    return text


def _render(mlir_text: str) -> str:
    schema_count = len(re.findall(r"\\bdsdl\\.schema\\b", mlir_text))
    digest = hashlib.sha256(mlir_text.encode("utf-8")).hexdigest()
    output = HEADER.format(
        schema_count=schema_count,
        sha256=digest,
        delimiter=DELIMITER,
        mlir_text=mlir_text,
    )
    if not output.endswith("\n"):
        output += "\n"
    return output


def _parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate embedded UAVCAN MLIR include.")
    parser.add_argument("--repo-root", default=str(DEFAULT_REPO_ROOT), help=f"Repository root (default: {DEFAULT_REPO_ROOT})")
    parser.add_argument("--uavcan-root", default=str(DEFAULT_UAVCAN_ROOT), help=f"UAVCAN DSDL root (default: {DEFAULT_UAVCAN_ROOT})")
    parser.add_argument("--dsdlc", default=None, help="Path to dsdlc executable (default: best-effort local build then PATH)")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help=f"Output include path (default: {DEFAULT_OUTPUT})")
    parser.add_argument("--check", action="store_true", help="Validate generated artifact is up to date.")
    return parser.parse_args(list(argv))


def main(argv: Iterable[str]) -> int:
    args = _parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    uavcan_root = Path(args.uavcan_root).resolve()
    output = Path(args.output).resolve()

    dsdlc = args.dsdlc if args.dsdlc else _find_default_dsdlc(repo_root)

    if not uavcan_root.exists():
        print(f"embedded-uavcan generation regression: missing UAVCAN root: {uavcan_root}")
        return 2

    try:
        mlir_text = _run_dsdlc(dsdlc, uavcan_root)
    except Exception as ex:  # noqa: BLE001
        print(f"embedded-uavcan generation regression: {ex}")
        return 1

    expected = _render(mlir_text)
    actual = output.read_text(encoding="utf-8") if output.exists() else ""

    if actual == expected:
        print("embedded UAVCAN MLIR catalog is up to date")
        return 0

    if args.check:
        print(
            "embedded-uavcan generation regression: "
            f"{output} is out of date; run tools/dsdlc/generate_embedded_uavcan_mlir.py"
        )
        return 1

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"updated: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
