# Generated by llvmdsdl <LLVMDSDL_VERSION> (Python backend).
# Source: fixtures.vendor.UnionTag.1.0
from __future__ import annotations

from dataclasses import dataclass, field

from fixtures_snapshot_py._runtime_loader import runtime as dsdl_runtime

LLVMDSDL_GENERATOR_VERSION = "<LLVMDSDL_VERSION>"
DSDL_FULL_NAME = "fixtures.vendor.UnionTag"
DSDL_VERSION_MAJOR = 1
DSDL_VERSION_MINOR = 0

@dataclass(slots=True)
class UnionTag_1_0:
    _tag: int = 0
    first: int | None = None
    second: int | None = None

    def serialize(self) -> bytes:
        return _serialize_UnionTag_1_0(self)

    @classmethod
    def deserialize(cls, data: bytes | bytearray | memoryview) -> "UnionTag_1_0":
        value, _consumed = _deserialize_UnionTag_1_0(bytes(data))
        return value

    def _serialize_to(self, writer: object) -> None:
        writer.write(self.serialize())

    @classmethod
    def _deserialize_from(cls, reader: object) -> "UnionTag_1_0":
        return cls.deserialize(reader.read())

def _serialize_UnionTag_1_0(value: UnionTag_1_0) -> bytes:
    out = bytearray(3)
    offset_bits = 0
    def mlir___llvmdsdl_plan_capacity_check__fixtures_vendor_UnionTag_1_0(capacity_bits: int) -> bool:
        return 24 <= capacity_bits
    def mlir___llvmdsdl_plan_validate_union_tag__fixtures_vendor_UnionTag_1_0(tag_value: int) -> bool:
        return (tag_value == 0) or (tag_value == 1)
    def mlir___llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__ser(value: int) -> int:
        return int(value) & 255
    def mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__ser(value: int) -> int:
        raw = int(value)
        if raw < 0:
            return 0
        if raw > 255:
            return 255
        return raw
    def mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__ser(value: int) -> int:
        raw = int(value)
        if raw < 0:
            return 0
        if raw > 65535:
            return 65535
        return raw
    
    if not mlir___llvmdsdl_plan_capacity_check__fixtures_vendor_UnionTag_1_0(len(out) * 8):
        raise ValueError("serialization buffer too small")
    tag = int(value._tag)
    if not mlir___llvmdsdl_plan_validate_union_tag__fixtures_vendor_UnionTag_1_0(tag):
        raise ValueError(f"invalid union tag {tag}")
    tag = int(mlir___llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__ser(tag))
    dsdl_runtime.write_unsigned(out, offset_bits, 8, tag, False)
    offset_bits += 8
    if tag == 0:
        if value.first is None:
            raise ValueError("union field 'first' missing for tag 0")
        dsdl_runtime.write_unsigned(out, offset_bits, 8, int(mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__ser(int(value.first))), True)
        offset_bits += 8
    elif tag == 1:
        if value.second is None:
            raise ValueError("union field 'second' missing for tag 1")
        dsdl_runtime.write_unsigned(out, offset_bits, 16, int(mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__ser(int(value.second))), True)
        offset_bits += 16
    else:
        raise ValueError(f"invalid union tag {tag}")
    aligned_offset_bits = dsdl_runtime.byte_length_for_bits(offset_bits) * 8
    for bit in range(offset_bits, aligned_offset_bits):
        dsdl_runtime.set_bit(out, bit, False)
    offset_bits = aligned_offset_bits
    used_bytes = dsdl_runtime.byte_length_for_bits(offset_bits)
    return bytes(out[:used_bytes])

def _deserialize_UnionTag_1_0(data: bytes | bytearray | memoryview) -> tuple[UnionTag_1_0, int]:
    data = bytes(data)
    def mlir___llvmdsdl_plan_validate_union_tag__fixtures_vendor_UnionTag_1_0(tag_value: int) -> bool:
        return (tag_value == 0) or (tag_value == 1)
    def mlir___llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__deser(value: int) -> int:
        return int(value) & 255
    def mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__deser(value: int) -> int:
        return int(value) & 255
    def mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__deser(value: int) -> int:
        return int(value) & 65535
    
    offset_bits = 0
    tag = int(dsdl_runtime.read_unsigned(data, offset_bits, 8))
    offset_bits += 8
    tag = int(mlir___llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__deser(tag))
    if not mlir___llvmdsdl_plan_validate_union_tag__fixtures_vendor_UnionTag_1_0(tag):
        raise ValueError(f"decoded invalid union tag {tag}")
    value = UnionTag_1_0(_tag=tag)
    if tag == 0:
        first_raw = dsdl_runtime.read_unsigned(data, offset_bits, 8)
        value.first = mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__deser(first_raw)
        offset_bits += 8
    elif tag == 1:
        second_raw = dsdl_runtime.read_unsigned(data, offset_bits, 16)
        value.second = mlir___llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__deser(second_raw)
        offset_bits += 16
    else:
        raise ValueError(f"decoded invalid union tag {tag}")
    offset_bits = dsdl_runtime.byte_length_for_bits(offset_bits) * 8
    consumed = min(len(data), dsdl_runtime.byte_length_for_bits(offset_bits))
    return value, consumed
