#!/usr/bin/env python3
#===----------------------------------------------------------------------===//
#
# Part of the OpenCyphal project, under the MIT licence
# SPDX-License-Identifier: MIT
#
#===----------------------------------------------------------------------===//

"""Compare generated snapshot text while ignoring llvm-dsdl tool-version fields."""

from __future__ import annotations

import difflib
import pathlib
import re
import sys

_NORMALIZE_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (
        re.compile(
            r"^(\s*(?:#|//)\s*Generated by llvmdsdl\s+)\d+\.\d+\.\d+(\b.*)$",
            re.MULTILINE,
        ),
        r"\1<LLVMDSDL_VERSION>\2",
    ),
    (
        re.compile(
            r'^(\s*(?:export\s+const\s+)?LLVMDSDL_GENERATOR_VERSION\s*=\s*")'
            r"\d+\.\d+\.\d+"
            r'(";\s*|"\s*)$',
            re.MULTILINE,
        ),
        r"\1<LLVMDSDL_VERSION>\2",
    ),
)


def _normalize_snapshot(text: str) -> str:
    normalized = text
    for pattern, replacement in _NORMALIZE_PATTERNS:
        normalized = pattern.sub(replacement, normalized)
    return normalized


def _load(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8", errors="strict")


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        sys.stderr.write("usage: compare_codegen_snapshot.py <actual> <expected>\n")
        return 2

    actual_path = pathlib.Path(argv[1])
    expected_path = pathlib.Path(argv[2])
    actual = _normalize_snapshot(_load(actual_path))
    expected = _normalize_snapshot(_load(expected_path))

    if actual == expected:
        return 0

    diff = difflib.unified_diff(
        expected.splitlines(keepends=True),
        actual.splitlines(keepends=True),
        fromfile=str(expected_path),
        tofile=str(actual_path),
    )
    sys.stderr.write("snapshot mismatch after version normalization:\n")
    sys.stderr.writelines(diff)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
