//===----------------------------------------------------------------------===//
///
/// @file
/// Implements DSDL MLIR attribute class glue code.
///
/// Most attribute definitions are generated by TableGen, with this file providing the compiled integration points.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/IR/DSDLAttrs.h"
#include "llvmdsdl/IR/DSDLDialect.h"  // IWYU pragma: keep

#include "llvm/ADT/TypeSwitch.h"  // IWYU pragma: keep
#include "mlir/IR/Builders.h"  // IWYU pragma: keep
#include "mlir/IR/DialectImplementation.h"  // IWYU pragma: keep
#include "mlir/IR/OpImplementation.h"  // IWYU pragma: keep

using namespace mlir;
using namespace mlir::dsdl;

#define GET_ATTRDEF_CLASSES
#include "llvmdsdl/IR/DSDLAttrs.cpp.inc"  // IWYU pragma: keep
