//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements DSDL MLIR type class glue code.
///
/// Most type definitions are generated by TableGen, with this file supplying compilation and registration hooks.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/IR/DSDLTypes.h"
#include "llvmdsdl/IR/DSDLDialect.h"  // IWYU pragma: keep

#include "llvm/ADT/TypeSwitch.h"            // IWYU pragma: keep
#include "mlir/IR/Builders.h"               // IWYU pragma: keep
#include "mlir/IR/DialectImplementation.h"  // IWYU pragma: keep
#include "mlir/IR/OpImplementation.h"       // IWYU pragma: keep

using namespace mlir;
using namespace mlir::dsdl;

#define GET_TYPEDEF_CLASSES
#include "llvmdsdl/IR/DSDLTypes.cpp.inc"  // IWYU pragma: keep
