cmake_minimum_required(VERSION 3.24)

foreach(var DSDLC UAVCAN_ROOT OUT_DIR)
  if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
    message(FATAL_ERROR "Missing required variable: ${var}")
  endif()
endforeach()

if(NOT DEFINED RUST_PROFILE OR "${RUST_PROFILE}" STREQUAL "")
  set(RUST_PROFILE "std")
endif()
if(NOT DEFINED RUST_RUNTIME_SPECIALIZATION OR
   "${RUST_RUNTIME_SPECIALIZATION}" STREQUAL "")
  set(RUST_RUNTIME_SPECIALIZATION "portable")
endif()
if(NOT DEFINED RUST_MEMORY_MODE OR "${RUST_MEMORY_MODE}" STREQUAL "")
  set(RUST_MEMORY_MODE "max-inline")
endif()
if(NOT DEFINED RUST_INLINE_THRESHOLD_BYTES OR
   "${RUST_INLINE_THRESHOLD_BYTES}" STREQUAL "")
  set(RUST_INLINE_THRESHOLD_BYTES "256")
endif()
if(NOT "${RUST_RUNTIME_SPECIALIZATION}" STREQUAL "portable" AND
   NOT "${RUST_RUNTIME_SPECIALIZATION}" STREQUAL "fast")
  message(FATAL_ERROR
    "Invalid RUST_RUNTIME_SPECIALIZATION value: ${RUST_RUNTIME_SPECIALIZATION}")
endif()
if(NOT "${RUST_MEMORY_MODE}" STREQUAL "max-inline" AND
   NOT "${RUST_MEMORY_MODE}" STREQUAL "inline-then-pool")
  message(FATAL_ERROR
    "Invalid RUST_MEMORY_MODE value: ${RUST_MEMORY_MODE}")
endif()
if(NOT RUST_INLINE_THRESHOLD_BYTES MATCHES "^[0-9]+$")
  message(FATAL_ERROR
    "Invalid RUST_INLINE_THRESHOLD_BYTES value: ${RUST_INLINE_THRESHOLD_BYTES}")
endif()
if(RUST_INLINE_THRESHOLD_BYTES LESS 1)
  message(FATAL_ERROR
    "RUST_INLINE_THRESHOLD_BYTES must be positive: ${RUST_INLINE_THRESHOLD_BYTES}")
endif()

if(NOT EXISTS "${DSDLC}")
  message(FATAL_ERROR "dsdlc executable not found: ${DSDLC}")
endif()

if(NOT EXISTS "${UAVCAN_ROOT}")
  message(FATAL_ERROR "uavcan root not found: ${UAVCAN_ROOT}")
endif()

file(REMOVE_RECURSE "${OUT_DIR}")
file(MAKE_DIRECTORY "${OUT_DIR}")

execute_process(
  COMMAND
    "${DSDLC}" --target-language rust
      "${UAVCAN_ROOT}"
      --outdir "${OUT_DIR}"
      --rust-crate-name "uavcan_dsdl_generated"
      --rust-profile "${RUST_PROFILE}"
      --rust-runtime-specialization "${RUST_RUNTIME_SPECIALIZATION}"
      --rust-memory-mode "${RUST_MEMORY_MODE}"
      --rust-inline-threshold-bytes "${RUST_INLINE_THRESHOLD_BYTES}"
  RESULT_VARIABLE gen_result
  OUTPUT_VARIABLE gen_stdout
  ERROR_VARIABLE gen_stderr
)
if(NOT gen_result EQUAL 0)
  message(STATUS "dsdlc stdout:\n${gen_stdout}")
  message(STATUS "dsdlc stderr:\n${gen_stderr}")
  message(FATAL_ERROR "uavcan rust generation failed")
endif()

foreach(required
    "${OUT_DIR}/Cargo.toml"
    "${OUT_DIR}/src/lib.rs"
    "${OUT_DIR}/src/dsdl_runtime.rs")
  if(NOT EXISTS "${required}")
    message(FATAL_ERROR "Missing required generated file: ${required}")
  endif()
endforeach()

file(READ "${OUT_DIR}/Cargo.toml" cargo_toml)
if(NOT cargo_toml MATCHES "\\[package\\.metadata\\.llvmdsdl\\]")
  message(FATAL_ERROR "Expected Cargo.toml llvmdsdl metadata section")
endif()
if(NOT cargo_toml MATCHES "rust-profile = \"${RUST_PROFILE}\"")
  message(FATAL_ERROR "Expected Cargo.toml rust-profile metadata to match RUST_PROFILE")
endif()
if(NOT cargo_toml MATCHES "rust-runtime-specialization = \"${RUST_RUNTIME_SPECIALIZATION}\"")
  message(FATAL_ERROR
    "Expected Cargo.toml rust-runtime-specialization metadata to match RUST_RUNTIME_SPECIALIZATION")
endif()
if(NOT cargo_toml MATCHES "rust-memory-mode = \"${RUST_MEMORY_MODE}\"")
  message(FATAL_ERROR "Expected Cargo.toml rust-memory-mode metadata to match RUST_MEMORY_MODE")
endif()
if(NOT cargo_toml MATCHES "rust-inline-threshold-bytes = ${RUST_INLINE_THRESHOLD_BYTES}")
  message(FATAL_ERROR
    "Expected Cargo.toml rust-inline-threshold-bytes metadata to match RUST_INLINE_THRESHOLD_BYTES")
endif()
if(NOT cargo_toml MATCHES "runtime-fast = \\[\\]")
  message(FATAL_ERROR "Expected Cargo.toml to declare runtime-fast feature")
endif()
if("${RUST_PROFILE}" STREQUAL "no-std-alloc")
  if("${RUST_RUNTIME_SPECIALIZATION}" STREQUAL "fast")
    if(NOT cargo_toml MATCHES "default = \\[\"runtime-fast\"\\]")
      message(FATAL_ERROR
        "Expected no-std fast Cargo.toml default features to include runtime-fast")
    endif()
  else()
    if(NOT cargo_toml MATCHES "default = \\[\\]")
      message(FATAL_ERROR
        "Expected no-std Cargo.toml default features to be empty")
    endif()
  endif()
else()
  if("${RUST_RUNTIME_SPECIALIZATION}" STREQUAL "fast")
    if(NOT cargo_toml MATCHES "default = \\[\"std\", \"runtime-fast\"\\]")
      message(FATAL_ERROR
        "Expected std fast Cargo.toml default features to include std and runtime-fast")
    endif()
  else()
    if(NOT cargo_toml MATCHES "default = \\[\"std\"\\]")
      message(FATAL_ERROR
        "Expected std Cargo.toml default features to include std")
    endif()
  endif()
endif()

file(GLOB_RECURSE dsdl_files "${UAVCAN_ROOT}/*.dsdl")
list(LENGTH dsdl_files dsdl_count)

file(GLOB_RECURSE rust_files "${OUT_DIR}/src/*.rs")
set(type_rs_files "")
foreach(rs IN LISTS rust_files)
  get_filename_component(name "${rs}" NAME)
  if(NOT name STREQUAL "lib.rs" AND
     NOT name STREQUAL "mod.rs" AND
     NOT name STREQUAL "dsdl_runtime.rs")
    list(APPEND type_rs_files "${rs}")
  endif()
endforeach()
list(LENGTH type_rs_files type_rs_count)

set(found_mlir_union_helper FALSE)
set(found_mlir_union_validate_helper FALSE)
set(found_mlir_union_validate_call FALSE)
set(found_mlir_capacity_check_helper FALSE)
set(found_mlir_capacity_check_call FALSE)
set(found_mlir_array_prefix_helper FALSE)
set(found_mlir_array_prefix_call FALSE)
set(found_mlir_array_validate_helper FALSE)
set(found_mlir_array_validate_call FALSE)
set(found_mlir_scalar_unsigned_helper FALSE)
set(found_mlir_scalar_unsigned_call FALSE)
set(found_mlir_scalar_signed_helper FALSE)
set(found_mlir_scalar_signed_call FALSE)
set(found_mlir_scalar_float_helper FALSE)
set(found_mlir_scalar_float_call FALSE)
set(found_mlir_delimiter_validate_helper FALSE)
set(found_mlir_delimiter_validate_call FALSE)
set(found_memory_mode_constant FALSE)
set(found_inline_threshold_constant FALSE)
set(found_pool_class_constant FALSE)
set(found_set_memory_contract_call FALSE)
set(found_reserve_with_pool_call FALSE)
set(found_passthrough_pool_provider_call FALSE)
set(found_backend_fallback_signature FALSE)
set(found_backend_array_length_fallback_signature FALSE)
set(found_backend_delimiter_fallback_signature FALSE)
set(found_backend_scalar_deser_fallback_signature FALSE)
foreach(rs IN LISTS type_rs_files)
  file(READ "${rs}" rs_text)
  if(rs_text MATCHES "mlir___llvmdsdl_plan_union_tag__")
    set(found_mlir_union_helper TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_validate_union_tag__")
    set(found_mlir_union_validate_helper TRUE)
  endif()
  if(rs_text MATCHES "let _err_union_tag = mlir___llvmdsdl_plan_validate_union_tag__")
    set(found_mlir_union_validate_call TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_capacity_check__")
    set(found_mlir_capacity_check_helper TRUE)
  endif()
  if(rs_text MATCHES "let _err_capacity = mlir___llvmdsdl_plan_capacity_check__")
    set(found_mlir_capacity_check_call TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_array_length_prefix__")
    set(found_mlir_array_prefix_helper TRUE)
  endif()
  if(rs_text MATCHES "let _count[0-9_]* = mlir___llvmdsdl_plan_array_length_prefix__")
    set(found_mlir_array_prefix_call TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_validate_array_length__")
    set(found_mlir_array_validate_helper TRUE)
  endif()
  if(rs_text MATCHES "let _len_rc[0-9_]* = mlir___llvmdsdl_plan_validate_array_length__")
    set(found_mlir_array_validate_call TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_scalar_unsigned__")
    set(found_mlir_scalar_unsigned_helper TRUE)
  endif()
  if(rs_text MATCHES "= mlir___llvmdsdl_plan_scalar_unsigned__.*__deser\\(")
    set(found_mlir_scalar_unsigned_call TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_scalar_signed__")
    set(found_mlir_scalar_signed_helper TRUE)
  endif()
  if(rs_text MATCHES "= mlir___llvmdsdl_plan_scalar_signed__.*__deser\\(")
    set(found_mlir_scalar_signed_call TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_scalar_float__")
    set(found_mlir_scalar_float_helper TRUE)
  endif()
  if(rs_text MATCHES "= mlir___llvmdsdl_plan_scalar_float__.*__deser\\(")
    set(found_mlir_scalar_float_call TRUE)
  endif()
  if(rs_text MATCHES "mlir___llvmdsdl_plan_validate_delimiter_header__")
    set(found_mlir_delimiter_validate_helper TRUE)
  endif()
  if(rs_text MATCHES "let _rc[0-9_]* = mlir___llvmdsdl_plan_validate_delimiter_header__")
    set(found_mlir_delimiter_validate_call TRUE)
  endif()
  if(rs_text MATCHES "__LLVMDSDL_MEMORY_MODE: crate::dsdl_runtime::DsdlMemoryMode")
    set(found_memory_mode_constant TRUE)
  endif()
  if(rs_text MATCHES "__LLVMDSDL_INLINE_THRESHOLD_BYTES: usize = [0-9]+usize")
    set(found_inline_threshold_constant TRUE)
  endif()
  if(rs_text MATCHES "__LLVMDSDL_POOL_CLASS_[A-Z0-9_]+: crate::dsdl_runtime::AllocationClassId")
    set(found_pool_class_constant TRUE)
  endif()
  if(rs_text MATCHES "\\.set_memory_contract\\(crate::dsdl_runtime::VarArrayMemoryContract::new\\(")
    set(found_set_memory_contract_call TRUE)
  endif()
  if(rs_text MATCHES "\\.reserve_with_pool\\(")
    set(found_reserve_with_pool_call TRUE)
  endif()
  if(rs_text MATCHES "crate::dsdl_runtime::PassthroughPoolProvider::default\\(")
    set(found_passthrough_pool_provider_call TRUE)
  endif()
  if(rs_text MATCHES "let mut _sat[0-9_]* = ")
    set(found_backend_fallback_signature TRUE)
  endif()
  if(rs_text MATCHES "\\.len\\(\\) > [0-9]+usize")
    set(found_backend_array_length_fallback_signature TRUE)
  endif()
  if(rs_text MATCHES "_size_bytes[0-9_]* > _remaining")
    set(found_backend_delimiter_fallback_signature TRUE)
  endif()
  if(rs_text MATCHES "self\\.[A-Za-z0-9_]+ = crate::dsdl_runtime::get_(u|i|f)")
    set(found_backend_scalar_deser_fallback_signature TRUE)
  endif()
endforeach()

if(NOT found_mlir_union_helper)
  message(FATAL_ERROR "Missing MLIR union-tag helper bindings in generated Rust files")
endif()
if(NOT found_mlir_union_validate_helper)
  message(FATAL_ERROR "Missing MLIR union-tag-validate helper bindings in generated Rust files")
endif()
if(NOT found_mlir_union_validate_call)
  message(FATAL_ERROR "Missing MLIR union-tag-validate helper call sites in generated Rust files")
endif()
if(NOT found_mlir_capacity_check_helper)
  message(FATAL_ERROR "Missing MLIR capacity-check helper bindings in generated Rust files")
endif()
if(NOT found_mlir_capacity_check_call)
  message(FATAL_ERROR "Missing MLIR capacity-check helper call sites in generated Rust files")
endif()
if(NOT found_mlir_array_prefix_helper)
  message(FATAL_ERROR "Missing MLIR array-prefix helper bindings in generated Rust files")
endif()
if(NOT found_mlir_array_prefix_call)
  message(FATAL_ERROR "Missing MLIR array-prefix helper call sites in generated Rust files")
endif()
if(NOT found_mlir_array_validate_helper)
  message(FATAL_ERROR "Missing MLIR array-validate helper bindings in generated Rust files")
endif()
if(NOT found_mlir_array_validate_call)
  message(FATAL_ERROR "Missing MLIR array-validate helper call sites in generated Rust files")
endif()
if(NOT found_mlir_scalar_unsigned_helper)
  message(FATAL_ERROR "Missing MLIR scalar-unsigned helper bindings in generated Rust files")
endif()
if(NOT found_mlir_scalar_unsigned_call)
  message(FATAL_ERROR "Missing MLIR scalar-unsigned helper call sites in generated Rust files")
endif()
if(NOT found_mlir_scalar_signed_helper)
  message(FATAL_ERROR "Missing MLIR scalar-signed helper bindings in generated Rust files")
endif()
if(NOT found_mlir_scalar_signed_call)
  message(FATAL_ERROR "Missing MLIR scalar-signed helper call sites in generated Rust files")
endif()
if(NOT found_mlir_scalar_float_helper)
  message(FATAL_ERROR "Missing MLIR scalar-float helper bindings in generated Rust files")
endif()
if(NOT found_mlir_scalar_float_call)
  message(FATAL_ERROR "Missing MLIR scalar-float helper call sites in generated Rust files")
endif()
if(NOT found_mlir_delimiter_validate_helper)
  message(FATAL_ERROR "Missing MLIR delimiter-validate helper bindings in generated Rust files")
endif()
if(NOT found_mlir_delimiter_validate_call)
  message(FATAL_ERROR "Missing MLIR delimiter-validate helper call sites in generated Rust files")
endif()
if(NOT found_memory_mode_constant)
  message(FATAL_ERROR "Missing Rust memory-mode constants in generated Rust files")
endif()
if(NOT found_inline_threshold_constant)
  message(FATAL_ERROR "Missing Rust inline-threshold constants in generated Rust files")
endif()
if(NOT found_pool_class_constant)
  message(FATAL_ERROR "Missing Rust pool class constants in generated Rust files")
endif()
if(NOT found_set_memory_contract_call)
  message(FATAL_ERROR "Missing Rust set_memory_contract calls in generated Rust files")
endif()
if(NOT found_reserve_with_pool_call)
  message(FATAL_ERROR "Missing Rust reserve_with_pool calls in generated Rust files")
endif()
if(NOT found_passthrough_pool_provider_call)
  message(FATAL_ERROR "Missing Rust PassthroughPoolProvider allocation routes in generated Rust files")
endif()
if(found_backend_fallback_signature)
  message(FATAL_ERROR "Found backend fallback saturation signatures in generated Rust files")
endif()
if(found_backend_array_length_fallback_signature)
  message(FATAL_ERROR "Found backend inline array-length fallback signatures in generated Rust files")
endif()
if(found_backend_delimiter_fallback_signature)
  message(FATAL_ERROR "Found backend inline delimiter fallback signatures in generated Rust files")
endif()
if(found_backend_scalar_deser_fallback_signature)
  message(FATAL_ERROR "Found backend scalar-deserialize fallback signatures in generated Rust files")
endif()

if(NOT dsdl_count EQUAL type_rs_count)
  message(FATAL_ERROR
    "Rust type file count mismatch: dsdl=${dsdl_count}, generated=${type_rs_count}")
endif()

message(STATUS
  "uavcan rust generation check passed (${RUST_PROFILE}, ${RUST_RUNTIME_SPECIALIZATION}): ${dsdl_count} DSDL -> ${type_rs_count} Rust type files")
