cmake_minimum_required(VERSION 3.24)

foreach(var DSDLC UAVCAN_ROOT OUT_DIR)
  if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
    message(FATAL_ERROR "Missing required variable: ${var}")
  endif()
endforeach()

if(NOT EXISTS "${DSDLC}")
  message(FATAL_ERROR "dsdlc executable not found: ${DSDLC}")
endif()
if(NOT EXISTS "${UAVCAN_ROOT}")
  message(FATAL_ERROR "uavcan root not found: ${UAVCAN_ROOT}")
endif()

if(NOT DEFINED PY_PACKAGE OR "${PY_PACKAGE}" STREQUAL "")
  set(PY_PACKAGE "uavcan_dsdl_generated_py")
endif()
if(NOT DEFINED PY_RUNTIME_SPECIALIZATION OR "${PY_RUNTIME_SPECIALIZATION}" STREQUAL "")
  set(PY_RUNTIME_SPECIALIZATION "portable")
endif()
if(NOT "${PY_RUNTIME_SPECIALIZATION}" STREQUAL "portable" AND
   NOT "${PY_RUNTIME_SPECIALIZATION}" STREQUAL "fast")
  message(FATAL_ERROR "Invalid PY_RUNTIME_SPECIALIZATION value: ${PY_RUNTIME_SPECIALIZATION}")
endif()
set(py_package_path "${PY_PACKAGE}")
string(REPLACE "." "/" py_package_path "${py_package_path}")
set(package_root "${OUT_DIR}/${py_package_path}")

file(REMOVE_RECURSE "${OUT_DIR}")
file(MAKE_DIRECTORY "${OUT_DIR}")

execute_process(
  COMMAND "${DSDLC}" --target-language python
    "${UAVCAN_ROOT}"
    --outdir "${OUT_DIR}"
    --py-package "${PY_PACKAGE}"
    --py-runtime-specialization "${PY_RUNTIME_SPECIALIZATION}"
  RESULT_VARIABLE gen_result
  OUTPUT_VARIABLE gen_stdout
  ERROR_VARIABLE gen_stderr
)
if(NOT gen_result EQUAL 0)
  message(STATUS "dsdlc stdout:\n${gen_stdout}")
  message(STATUS "dsdlc stderr:\n${gen_stderr}")
  message(FATAL_ERROR "uavcan Python generation failed")
endif()

foreach(required
    "${OUT_DIR}/pyproject.toml"
    "${package_root}/__init__.py"
    "${package_root}/_dsdl_runtime.py"
    "${package_root}/_runtime_loader.py"
    "${package_root}/py.typed"
    "${package_root}/llvmdsdl_codegen.json")
  if(NOT EXISTS "${required}")
    message(FATAL_ERROR "Missing required generated file: ${required}")
  endif()
endforeach()

file(READ "${OUT_DIR}/pyproject.toml" pyproject_toml)
if(NOT pyproject_toml MATCHES
      "\\[build-system\\]")
  message(FATAL_ERROR "Generated pyproject.toml is missing [build-system]")
endif()
if(NOT pyproject_toml MATCHES
      "\\[tool\\.setuptools\\.package-data\\]")
  message(FATAL_ERROR "Generated pyproject.toml is missing [tool.setuptools.package-data]")
endif()
if(NOT pyproject_toml MATCHES "_dsdl_runtime_accel\\*\\.so")
  message(FATAL_ERROR "Generated pyproject.toml is missing accelerator .so package-data pattern")
endif()
if(NOT pyproject_toml MATCHES "_dsdl_runtime_accel\\*\\.dylib")
  message(FATAL_ERROR "Generated pyproject.toml is missing accelerator .dylib package-data pattern")
endif()
if(NOT pyproject_toml MATCHES "_dsdl_runtime_accel\\*\\.pyd")
  message(FATAL_ERROR "Generated pyproject.toml is missing accelerator .pyd package-data pattern")
endif()

file(READ "${package_root}/llvmdsdl_codegen.json" metadata_json)
if(NOT metadata_json MATCHES
      "\"pythonRuntimeSpecialization\"[ \t\r\n]*:[ \t\r\n]*\"${PY_RUNTIME_SPECIALIZATION}\"")
  message(FATAL_ERROR "Python generation metadata does not match specialization=${PY_RUNTIME_SPECIALIZATION}")
endif()

file(GLOB_RECURSE dsdl_files "${UAVCAN_ROOT}/*.dsdl")
list(LENGTH dsdl_files dsdl_count)

file(GLOB_RECURSE py_files "${package_root}/*.py")
set(type_py_files "")
foreach(py IN LISTS py_files)
  get_filename_component(name "${py}" NAME)
  if(NOT name STREQUAL "__init__.py" AND
     NOT name STREQUAL "_dsdl_runtime.py" AND
     NOT name STREQUAL "_runtime_loader.py")
    list(APPEND type_py_files "${py}")
  endif()
endforeach()
list(LENGTH type_py_files type_py_count)

if(NOT dsdl_count EQUAL type_py_count)
  message(FATAL_ERROR
    "Python type file count mismatch: dsdl=${dsdl_count}, generated=${type_py_count}")
endif()

set(found_dataclass FALSE)
set(found_serialize FALSE)
set(found_deserialize FALSE)
set(found_metadata_constant FALSE)
set(found_mlir_union_helper FALSE)
set(found_mlir_union_validate_helper FALSE)
set(found_mlir_union_validate_call FALSE)
set(found_mlir_capacity_check_helper FALSE)
set(found_mlir_capacity_check_call FALSE)
set(found_mlir_array_prefix_helper FALSE)
set(found_mlir_array_prefix_call FALSE)
set(found_mlir_array_validate_helper FALSE)
set(found_mlir_array_validate_call FALSE)
set(found_mlir_scalar_unsigned_helper FALSE)
set(found_mlir_scalar_unsigned_call FALSE)
set(found_mlir_scalar_signed_helper FALSE)
set(found_mlir_scalar_signed_call FALSE)
set(found_mlir_scalar_float_helper FALSE)
set(found_mlir_scalar_float_call FALSE)
set(found_mlir_delimiter_validate_helper FALSE)
set(found_mlir_delimiter_validate_call FALSE)
set(found_backend_fallback_signature FALSE)
set(found_backend_array_length_fallback_signature FALSE)
set(found_backend_delimiter_fallback_signature FALSE)
set(found_backend_scalar_deser_fallback_signature FALSE)
foreach(py IN LISTS type_py_files)
  file(READ "${py}" text)
  if(text MATCHES "@dataclass\\(slots=True\\)")
    set(found_dataclass TRUE)
  endif()
  if(text MATCHES "def serialize\\(self\\) -> bytes")
    set(found_serialize TRUE)
  endif()
  if(text MATCHES "def deserialize\\(cls, data: bytes \\| bytearray \\| memoryview\\)")
    set(found_deserialize TRUE)
  endif()
  if(text MATCHES "DSDL_FULL_NAME = ")
    set(found_metadata_constant TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_union_tag__")
    set(found_mlir_union_helper TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_validate_union_tag__")
    set(found_mlir_union_validate_helper TRUE)
  endif()
  if(text MATCHES "if not mlir___llvmdsdl_plan_validate_union_tag__")
    set(found_mlir_union_validate_call TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_capacity_check__")
    set(found_mlir_capacity_check_helper TRUE)
  endif()
  if(text MATCHES "if not mlir___llvmdsdl_plan_capacity_check__")
    set(found_mlir_capacity_check_call TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_array_length_prefix__")
    set(found_mlir_array_prefix_helper TRUE)
  endif()
  if(text MATCHES "write_unsigned\\(.*mlir___llvmdsdl_plan_array_length_prefix__")
    set(found_mlir_array_prefix_call TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_validate_array_length__")
    set(found_mlir_array_validate_helper TRUE)
  endif()
  if(text MATCHES "if not mlir___llvmdsdl_plan_validate_array_length__")
    set(found_mlir_array_validate_call TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_scalar_unsigned__")
    set(found_mlir_scalar_unsigned_helper TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_scalar_unsigned__.*__deser\\(")
    set(found_mlir_scalar_unsigned_call TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_scalar_signed__")
    set(found_mlir_scalar_signed_helper TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_scalar_signed__.*__deser\\(")
    set(found_mlir_scalar_signed_call TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_scalar_float__")
    set(found_mlir_scalar_float_helper TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_scalar_float__.*__deser\\(")
    set(found_mlir_scalar_float_call TRUE)
  endif()
  if(text MATCHES "mlir___llvmdsdl_plan_validate_delimiter_header__")
    set(found_mlir_delimiter_validate_helper TRUE)
  endif()
  if(text MATCHES "if not mlir___llvmdsdl_plan_validate_delimiter_header__")
    set(found_mlir_delimiter_validate_call TRUE)
  endif()
  if(text MATCHES "_sat[0-9_]* = ")
    set(found_backend_fallback_signature TRUE)
  endif()
  if(text MATCHES "if [A-Za-z0-9_]+_len > [0-9]+")
    set(found_backend_array_length_fallback_signature TRUE)
  endif()
  if(text MATCHES "_size_bytes[0-9_]* > _remaining")
    set(found_backend_delimiter_fallback_signature TRUE)
  endif()
  if(text MATCHES "value\\.[A-Za-z0-9_]+ = dsdl_runtime\\.read_(unsigned|signed|float)\\(")
    set(found_backend_scalar_deser_fallback_signature TRUE)
  endif()
endforeach()

if(NOT found_dataclass)
  message(FATAL_ERROR "Generated Python files are missing dataclass declarations")
endif()
if(NOT found_serialize)
  message(FATAL_ERROR "Generated Python files are missing serialize() methods")
endif()
if(NOT found_deserialize)
  message(FATAL_ERROR "Generated Python files are missing deserialize() methods")
endif()
if(NOT found_metadata_constant)
  message(FATAL_ERROR "Generated Python files are missing DSDL metadata constants")
endif()
if(NOT found_mlir_union_helper)
  message(FATAL_ERROR "Missing MLIR union-tag helper markers in generated Python files")
endif()
if(NOT found_mlir_union_validate_helper)
  message(FATAL_ERROR "Missing MLIR union-tag-validate helper markers in generated Python files")
endif()
if(NOT found_mlir_union_validate_call)
  message(FATAL_ERROR "Missing MLIR union-tag-validate helper call sites in generated Python files")
endif()
if(NOT found_mlir_capacity_check_helper)
  message(FATAL_ERROR "Missing MLIR capacity-check helper markers in generated Python files")
endif()
if(NOT found_mlir_capacity_check_call)
  message(FATAL_ERROR "Missing MLIR capacity-check helper call sites in generated Python files")
endif()
if(NOT found_mlir_array_prefix_helper)
  message(FATAL_ERROR "Missing MLIR array-prefix helper markers in generated Python files")
endif()
if(NOT found_mlir_array_prefix_call)
  message(FATAL_ERROR "Missing MLIR array-prefix helper call sites in generated Python files")
endif()
if(NOT found_mlir_array_validate_helper)
  message(FATAL_ERROR "Missing MLIR array-validate helper markers in generated Python files")
endif()
if(NOT found_mlir_array_validate_call)
  message(FATAL_ERROR "Missing MLIR array-validate helper call sites in generated Python files")
endif()
if(NOT found_mlir_scalar_unsigned_helper)
  message(FATAL_ERROR "Missing MLIR scalar-unsigned helper markers in generated Python files")
endif()
if(NOT found_mlir_scalar_unsigned_call)
  message(FATAL_ERROR "Missing MLIR scalar-unsigned helper call sites in generated Python files")
endif()
if(NOT found_mlir_scalar_signed_helper)
  message(FATAL_ERROR "Missing MLIR scalar-signed helper markers in generated Python files")
endif()
if(NOT found_mlir_scalar_signed_call)
  message(FATAL_ERROR "Missing MLIR scalar-signed helper call sites in generated Python files")
endif()
if(NOT found_mlir_scalar_float_helper)
  message(FATAL_ERROR "Missing MLIR scalar-float helper markers in generated Python files")
endif()
if(NOT found_mlir_scalar_float_call)
  message(FATAL_ERROR "Missing MLIR scalar-float helper call sites in generated Python files")
endif()
if(NOT found_mlir_delimiter_validate_helper)
  message(FATAL_ERROR "Missing MLIR delimiter-validate helper markers in generated Python files")
endif()
if(NOT found_mlir_delimiter_validate_call)
  message(FATAL_ERROR "Missing MLIR delimiter-validate helper call sites in generated Python files")
endif()
if(found_backend_fallback_signature)
  message(FATAL_ERROR "Found backend fallback saturation signatures in generated Python files")
endif()
if(found_backend_array_length_fallback_signature)
  message(FATAL_ERROR "Found backend inline array-length fallback signatures in generated Python files")
endif()
if(found_backend_delimiter_fallback_signature)
  message(FATAL_ERROR "Found backend inline delimiter fallback signatures in generated Python files")
endif()
if(found_backend_scalar_deser_fallback_signature)
  message(FATAL_ERROR "Found backend scalar-deserialize fallback signatures in generated Python files")
endif()

message(STATUS
  "uavcan Python generation check passed: ${dsdl_count} DSDL -> ${type_py_count} Python type files")
