cmake_minimum_required(VERSION 3.24)

foreach(var DSDLC UAVCAN_ROOT OUT_DIR)
  if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
    message(FATAL_ERROR "Missing required variable: ${var}")
  endif()
endforeach()

if(NOT EXISTS "${DSDLC}")
  message(FATAL_ERROR "dsdlc executable not found: ${DSDLC}")
endif()

if(NOT EXISTS "${UAVCAN_ROOT}")
  message(FATAL_ERROR "uavcan root not found: ${UAVCAN_ROOT}")
endif()

file(REMOVE_RECURSE "${OUT_DIR}")
file(MAKE_DIRECTORY "${OUT_DIR}")

execute_process(
  COMMAND
    "${DSDLC}" go
      --root-namespace-dir "${UAVCAN_ROOT}"
      --strict
      --out-dir "${OUT_DIR}"
      --go-module "uavcan_dsdl_generated"
  RESULT_VARIABLE gen_result
  OUTPUT_VARIABLE gen_stdout
  ERROR_VARIABLE gen_stderr
)
if(NOT gen_result EQUAL 0)
  message(STATUS "dsdlc stdout:\n${gen_stdout}")
  message(STATUS "dsdlc stderr:\n${gen_stderr}")
  message(FATAL_ERROR "uavcan Go generation failed")
endif()

foreach(required
    "${OUT_DIR}/go.mod"
    "${OUT_DIR}/dsdlruntime/dsdl_runtime.go")
  if(NOT EXISTS "${required}")
    message(FATAL_ERROR "Missing required generated file: ${required}")
  endif()
endforeach()

file(GLOB_RECURSE dsdl_files "${UAVCAN_ROOT}/*.dsdl")
list(LENGTH dsdl_files dsdl_count)

file(GLOB_RECURSE go_files "${OUT_DIR}/*.go")
set(type_go_files "")
foreach(gf IN LISTS go_files)
  get_filename_component(name "${gf}" NAME)
  if(NOT name STREQUAL "dsdl_runtime.go")
    list(APPEND type_go_files "${gf}")
  endif()
endforeach()
list(LENGTH type_go_files type_go_count)

set(found_mlir_union_helper FALSE)
set(found_mlir_union_validate_helper FALSE)
set(found_mlir_capacity_check_helper FALSE)
set(found_mlir_array_prefix_helper FALSE)
set(found_mlir_array_validate_helper FALSE)
set(found_mlir_scalar_unsigned_helper FALSE)
set(found_mlir_scalar_signed_helper FALSE)
set(found_mlir_scalar_float_helper FALSE)
set(found_mlir_delimiter_validate_helper FALSE)
set(found_runtime_write_call FALSE)
set(found_runtime_read_call FALSE)
foreach(gf IN LISTS type_go_files)
  file(READ "${gf}" go_text)
  if(go_text MATCHES "__llvmdsdl_plan_union_tag__")
    set(found_mlir_union_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_validate_union_tag__")
    set(found_mlir_union_validate_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_capacity_check__")
    set(found_mlir_capacity_check_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_array_length_prefix__")
    set(found_mlir_array_prefix_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_validate_array_length__")
    set(found_mlir_array_validate_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_scalar_unsigned__")
    set(found_mlir_scalar_unsigned_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_scalar_signed__")
    set(found_mlir_scalar_signed_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_scalar_float__")
    set(found_mlir_scalar_float_helper TRUE)
  endif()
  if(go_text MATCHES "__llvmdsdl_plan_validate_delimiter_header__")
    set(found_mlir_delimiter_validate_helper TRUE)
  endif()
  if(go_text MATCHES "dsdlruntime\\.SetUxx\\(")
    set(found_runtime_write_call TRUE)
  endif()
  if(go_text MATCHES "dsdlruntime\\.GetU64\\(")
    set(found_runtime_read_call TRUE)
  endif()
endforeach()

if(NOT found_mlir_union_helper)
  message(FATAL_ERROR "Missing MLIR union-tag helper markers in generated Go files")
endif()
if(NOT found_mlir_union_validate_helper)
  message(FATAL_ERROR "Missing MLIR union-tag-validate helper markers in generated Go files")
endif()
if(NOT found_mlir_capacity_check_helper)
  message(FATAL_ERROR "Missing MLIR capacity-check helper markers in generated Go files")
endif()
if(NOT found_mlir_array_prefix_helper)
  message(FATAL_ERROR "Missing MLIR array-prefix helper markers in generated Go files")
endif()
if(NOT found_mlir_array_validate_helper)
  message(FATAL_ERROR "Missing MLIR array-validate helper markers in generated Go files")
endif()
if(NOT found_mlir_scalar_unsigned_helper)
  message(FATAL_ERROR "Missing MLIR scalar-unsigned helper markers in generated Go files")
endif()
if(NOT found_mlir_scalar_signed_helper)
  message(FATAL_ERROR "Missing MLIR scalar-signed helper markers in generated Go files")
endif()
if(NOT found_mlir_scalar_float_helper)
  message(FATAL_ERROR "Missing MLIR scalar-float helper markers in generated Go files")
endif()
if(NOT found_mlir_delimiter_validate_helper)
  message(FATAL_ERROR "Missing MLIR delimiter-validate helper markers in generated Go files")
endif()
if(NOT found_runtime_write_call)
  message(FATAL_ERROR "Generated Go files are missing dsdlruntime.SetUxx calls; serialize path appears stubbed")
endif()
if(NOT found_runtime_read_call)
  message(FATAL_ERROR "Generated Go files are missing dsdlruntime.GetU64 calls; deserialize path appears stubbed")
endif()

if(NOT dsdl_count EQUAL type_go_count)
  message(FATAL_ERROR
    "Go type file count mismatch: dsdl=${dsdl_count}, generated=${type_go_count}")
endif()

message(STATUS
  "uavcan Go generation check passed: ${dsdl_count} DSDL -> ${type_go_count} Go type files")
